version: '3.4'

services:
  ai-flow-database:
    image: postgres:13
    container_name: ai-flow-database
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./ai-flow-db/postgres:/var/lib/postgresql/data

  ai-flow:
    image: orientis/ai-flow:0.1.4
    container_name: ai-flow
    depends_on: 
      - ai-flow-database
    ports:
      - "8082:80"
    restart: always
    volumes:
      - ./ai-flow-appdata:/usr/share/orientis/ai-flow-appdata    
    